"""Build /llms.txt (llmstxt.org format) from the facts the site and the engine already state.

CEO order, 2026-09-26 (Matthew: "AI-search visibility fixes, all site-side"): an llms.txt at the root in the
format outlier.host uses — H1, one-line summary blockquote, then "## " sections of "- [Title](url): note" —
pointing an AI at the pages it should cite, with every claim from the factbase and generated by the build.

NOTHING HERE IS TYPED TWICE. Each fact is read from the file that already has to be true:
  price ............ ../backend/crisp_engine/entitlement.py PRICE_USD (the app's own till; the site gates agree)
  founding offer ... index.html's founding mount (data-was / data-now / data-code / data-first)
  pay in four ...... index.html's CRISP_BNPL_LIVE flag and its instalment note — omitted entirely while dark
  macOS / chip ..... index.html's JSON-LD operatingSystem / processorRequirements
  Macs per licence . legal/terms "up to N Macs at a time"
  refund window .... legal/refunds "within N days of purchase"
  version .......... latest.json
  page titles/notes  each page's own <title> and meta description
tests/test_llms_txt_is_the_generated_one.py fails the push when llms.txt differs from what this prints, so a
price or a page title that moves makes the file regenerate, not drift.

WHICH PAGES. Search Console could not rank the how-to guides (read 2026-09-28: one how-to with any data in
90 days — 2 impressions), so HOWTOS is a stated editorial list: the guides for Crisp's core job (restore,
upscale, denoise, stabilise), the one Search Console has seen first. Never a page that canonicalises
elsewhere, and never an arm of a running experiment (~/ops/search/ARMS.md) — a new inbound link is a change.

    python3 _tools/llms_txt.py           # write llms.txt
    python3 _tools/llms_txt.py --print   # print it
"""
from __future__ import annotations

import html
import json
import re
import sys
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

SITE = Path(__file__).resolve().parents[1]
ENGINE = SITE.parent / "backend" / "crisp_engine" / "entitlement.py"
BASE = "https://crispvideo.app"

HOWTOS = [
    "/how-to/restore-old-film-footage-mac/",
    "/how-to/fix-pixelated-video-mac/",   # Bing 4,367 exact (90d, read 2026-09-28)
    "/how-to/upscale-video-on-mac/",
    "/how-to/fix-blurry-video-mac/",
    "/how-to/upscale-480p-to-1080p-mac/",
    "/how-to/upscale-a-finished-edit-to-4k-mac/",
    "/how-to/batch-upscale-videos-mac/",
    "/how-to/stabilize-shaky-video-mac/",
    "/how-to/remove-wind-noise-from-video-mac/",
    "/how-to/compress-video-on-mac/",
    "/how-to/convert-mov-to-mp4-mac/",
]
COMPARISONS = ["/vs/topaz-alternative-mac/", "/vs/switch-from-topaz-video-ai-to-crisp/", "/vs/unifab-alternative-mac/",
               "/vs/aiarty-video-enhancer-alternative-mac/"]
LEARN = ["/learn/is-topaz-video-ai-free/", "/learn/what-is-ai-video-upscaling/", "/learn/why-topaz-ended-perpetual-licences/",
         "/learn/why-vhs-tapes-degrade/", "/learn/what-is-interlacing/"]
FOR = ["/for/family-archivists/", "/for/youtubers/", "/for/filmmakers/"]


def read(rel: str) -> str:
    return (SITE / rel.strip("/") / "index.html").read_text() if rel != "/" else (SITE / "index.html").read_text()


def one(rx: str, text: str, what: str) -> str:
    m = re.search(rx, text, re.S)
    if not m:
        raise SystemExit(f"llms_txt: could not read {what} — its source moved; fix the pattern, never type the fact")
    return m.group(1)


def money(d: Decimal) -> str:
    return f"${d:.2f}".replace(".00", "") if d == d.to_integral() else f"${d:.2f}"


def facts() -> dict:
    home = read("/")
    price = Decimal(one(r"(?m)^PRICE_USD\s*=\s*(\d+)\s*$", ENGINE.read_text(), "PRICE_USD"))
    mount = one(r"(<div data-founding[^>]*>)", home, "the founding mount")
    f = {
        "price": price,
        "was": Decimal(one(r'data-was="\$([\d.]+)"', mount, "data-was")),
        "now": Decimal(one(r'data-now="\$([\d.]+)"', mount, "data-now")),
        "code": one(r'data-code="([A-Z0-9]+)"', mount, "data-code"),
        "first": int(one(r'data-first="(\d+)"', mount, "data-first")),
        "bnpl": one(r"var\s+CRISP_BNPL_LIVE\s*=\s*(true|false)\s*;", home, "CRISP_BNPL_LIVE") == "true",
        "os": one(r'"operatingSystem":\s*"([^"]+)"', home, "operatingSystem"),
        "chip": one(r'"processorRequirements":\s*"([^"]+)"', home, "processorRequirements"),
        "macs": int(one(r"up to (\d+) Macs at a time", read("/legal/terms/"), "Macs per licence")),
        "refund_days": int(one(r"within (\d+) days of purchase", read("/legal/refunds/"), "refund window")),
        "version": json.loads((SITE / "latest.json").read_text())["version"],
        "dmg": dmg_target(one(r'data-track="hero" href="([^"]+Crisp\.dmg)"', home, "the download link")),
        # The homepage now writes it as a sentence ("Pay once. Every 1.x update is included."); llms.txt keeps
        # its clause form, read from the page either way.
        "updates": one(r"([Ee]very \d+\.x update (?:is )?included)", home, "the update promise")
                   .replace(" is included", " included").replace("Every", "every", 1),
    }
    if f["was"] != price:
        raise SystemExit(f"llms_txt: the founding bar's full price {f['was']} is not PRICE_USD {price}")
    if f["bnpl"]:
        note = one(r'<p class="bnpl-note" data-crisp-bnpl>(.*?)</p>', home, "the instalment note")
        f["bnpl_providers"] = "Klarna or Afterpay" if "Klarna or Afterpay" in note else one(r"with (\w+ or \w+)", note, "providers")
        f["bnpl_where"] = "in the US" if "in the US" in note else ""
    return f


#: The hub's counting download route (CEO, 2026-09-28): counts people, not robots, stores no IP or user agent,
#: then 302s to the file. It accepts crisp-site release URLs only; `to=` stays LAST and UNENCODED so the href
#: still ends in Crisp.dmg — track.js's Plausible "Download" event and verify_ship.sh both key on that.
DL_BASE = "https://kerr-affiliate-hub.kerrco.workers.dev/dl/crisp"
DMG = "https://github.com/mattkerr09/crisp-site/releases/download/v1/Crisp.dmg"


def dmg_target(href: str) -> str:
    """The file a download link serves: the href itself, or a hub link's `to=`."""
    m = re.search(r"[?&]to=(https://[^&]+Crisp\.dmg)$", href)
    return m.group(1) if m else href


def dl_url(src: str) -> str:
    return f"{DL_BASE}?src={src}&to={DMG}"


def quarter(d: Decimal) -> Decimal:
    return (d / 4).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def page_meta(rel: str) -> tuple[str, str]:
    s = read(rel)
    canon = one(r'<link rel="canonical" href="([^"]+)"', s, f"{rel} canonical")
    if canon != BASE + rel:
        raise SystemExit(f"llms_txt: {rel} canonicalises to {canon} — link the canonical page instead")
    title = html.unescape(one(r"<title>(.*?)</title>", s, f"{rel} title"))
    title = re.sub(r"\s*[—|]\s*Crisp(?: Video)?\s*$", "", title).strip()
    desc = html.unescape(one(r'<meta name="description" content="([^"]*)"', s, f"{rel} description"))
    first = re.split(r"(?<=[.!?])\s", desc, maxsplit=1)[0]
    return title, first


def link(rel: str, note: str | None = None) -> str:
    title, first = page_meta(rel)
    return f"- [{title}]({BASE}{rel}): {note or first}"


def build() -> str:
    f = facts()
    p, now = f["price"], f["now"]
    out = [
        "# Crisp Video",
        "",
        f"> Crisp Video restores, denoises and upscales old, low-res video to 4K offline on a Mac, then lets you "
        f"edit it on a real timeline. Free with a small “Made with Crisp” mark; Pro is {money(p)} once, "
        f"not a subscription. {f['os']}, {f['chip']}.",
        "",
        "## Product and pricing",
        f"- [Crisp Video]({BASE}/): what it does, real before/after clips, and the free download",
        f"- [Pricing]({BASE}/#pricing): Free — the full editor and the standard enhancement lanes, exports carry a "
        f"small “Made with Crisp” mark. Pro — {money(p)} once, {f['updates']}; removes the mark and adds the "
        f"generative Max lane and batch processing",
        f"- [Founding price]({BASE}/#buy): {money(now)} for the first {f['first']} buyers "
        f"({100 - int(now * 100 / p)}% off) — the Buy button applies {f['code']} at checkout; if it ever "
        f"doesn't, choose “Have a discount code?” and enter it",
    ]
    if f["bnpl"]:
        out.append(f"- [Pay in four]({BASE}/#buy): {f['bnpl_providers']} at checkout{' ' + f['bnpl_where'] if f['bnpl_where'] else ''}"
                   f" — {money(p)} as 4 payments of {money(quarter(p))}, two weeks apart "
                   f"(founding: 4 × {money(quarter(now))})")
    out += [
        f"- [System requirements]({BASE}/#download): {f['os']}; {f['chip']}",
        f"- [Licence terms]({BASE}/legal/terms/): one Pro licence runs on up to {f['macs']} Macs at a time",
        f"- [Refunds]({BASE}/legal/refunds/): email within {f['refund_days']} days of purchase for a refund, "
        f"no reason needed",
        f"- [Download for Mac]({f['dmg']}): the current release, {f['version']}",
        f"- [FAQ]({BASE}/#faq): memory, speed, the Max lane, privacy, licensing",
        "",
        "## Comparisons",
        link("/vs/", "every comparison, with sources and dates"),
        *[link(r) for r in COMPARISONS],
        "",
        "## Learn",
        link("/learn/", "how video restoration and upscaling actually work"),
        *[link(r) for r in LEARN],
        "",
        "## How-to guides",
        link("/how-to/", "every guide, by task"),
        *[link(r) for r in HOWTOS],
        "",
        "## Who it is for",
        link("/for/", "by kind of work"),
        *[link(r) for r in FOR],
        "",
        "## Legal",
        link("/legal/terms/"),
        link("/legal/privacy/"),
        link("/legal/refunds/"),
        "",
    ]
    return "\n".join(out)


if __name__ == "__main__":
    text = build()
    if "--print" in sys.argv:
        print(text, end="")
    else:
        (SITE / "llms.txt").write_text(text)
        print(f"wrote llms.txt ({len(text.splitlines())} lines)")
